/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as MealPlansRouteImport } from './routes/meal-plans'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as MealPlansNewRouteImport } from './routes/meal-plans/new'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansRoute = MealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansNewRoute = MealPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MealPlansRoute,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/recipes': typeof RecipesRouteWithChildren
  '/meal-plans/new': typeof MealPlansNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/meal-plans/new': typeof MealPlansNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/meal-plans': typeof MealPlansRouteWithChildren
  '/recipes': typeof RecipesRouteWithChildren
  '/meal-plans/new': typeof MealPlansNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/meal-plans'
    | '/recipes'
    | '/meal-plans/new'
    | '/recipes/new'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/$' | '/meal-plans' | '/meal-plans/new' | '/recipes/new' | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/meal-plans'
    | '/recipes'
    | '/meal-plans/new'
    | '/recipes/new'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  MealPlansRoute: typeof MealPlansRouteWithChildren
  RecipesRoute: typeof RecipesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans': {
      id: '/meal-plans'
      path: '/meal-plans'
      fullPath: '/meal-plans'
      preLoaderRoute: typeof MealPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/new': {
      id: '/meal-plans/new'
      path: '/new'
      fullPath: '/meal-plans/new'
      preLoaderRoute: typeof MealPlansNewRouteImport
      parentRoute: typeof MealPlansRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof RecipesRoute
    }
  }
}

interface MealPlansRouteChildren {
  MealPlansNewRoute: typeof MealPlansNewRoute
}

const MealPlansRouteChildren: MealPlansRouteChildren = {
  MealPlansNewRoute: MealPlansNewRoute,
}

const MealPlansRouteWithChildren = MealPlansRoute._addFileChildren(
  MealPlansRouteChildren,
)

interface RecipesRouteChildren {
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesNewRoute: RecipesNewRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  MealPlansRoute: MealPlansRouteWithChildren,
  RecipesRoute: RecipesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
